### PR TITLE
Fix name mismatch warnings

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
We are happily using `backward_ros` on MoveIt. Since the transition of Rolling to Jammy (thus to default cmake to be updated to 3.22), we are getting a flood of warnings related to `FindPackageHandleStandardArgs` every time we find package to `backward_ros`. This should hopefully fix it. We would be more than delighted for a new release of `backward_ros` on Rolling, so we don't have this flood.

Hope this makes sense. The fix was inspired from the same problem in catkin, [here](https://github.com/ros/catkin/pull/1093).

You can find a sample warning below:

```
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (libbfd)
  does not match the name of the calling package (backward_ros).  This can
  lead to problems in calling code that expects `find_package` result
  variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /opt/ros/rolling/share/backward_ros/cmake/BackwardConfig.cmake:66 (find_package_handle_standard_args)
  /opt/ros/rolling/share/backward_ros/cmake/backward_rosConfig.cmake:41 (include)
  /root/ws_moveit2/install/moveit_common/share/moveit_common/cmake/moveit_package.cmake:36 (find_package)
  CMakeLists.txt:6 (moveit_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
Friendly ping to @v-lopez, to see if this makes sense.

**Comment by v-lopez** [comment]
LGTM, but I am no longer working at PAL Robotics, pinging @jordan-palacios.

**Comment by vatanaksoytezer** [comment]
Another friendly ping to @jordan-palacios, to see if we can merge this and get a rolling release so we (and any package using this on rolling) is free of warnings.

**Comment by jordan-palacios** [comment]
Thanks for the collaboration. And sorry for the delay.

We'll try to release this ASAP.

**Comment by vatanaksoytezer** [comment]
Thanks a lot Jordan, we appreciate all the help!

**Comment by saikishor** [comment]
Hello @vatanaksoytezer,

We have requested for the release in the rolling distro. FYI: https://github.com/ros/rosdistro/pull/32613

Best Regards,
PAL Robotics Team.

**Comment by vatanaksoytezer** [comment]
@saikishor we appreciate the effort and the fast action, thank you very much!

**Comment by saikishor** [comment]
Hello @vatanaksoytezer,

The package is already merged to rosdistro upstream : https://github.com/ros/rosdistro/pull/32647

Thank you.

**Pull request merged**
